#!/usr/bin/env sh
# Print the Homebrew formula for a release: scripts/formula.sh 0.1.2 SHA256SUMS
# SHA256SUMS is the file the release workflow writes (sha256sum output, one line per asset).
set -eu
v="$1"; sums="$2"
sha() { grep "polygo-v$v-$1.tar.gz" "$sums" | cut -d' ' -f1; }
for a in aarch64-darwin x86_64-darwin aarch64-linux x86_64-linux; do
  [ -n "$(sha "$a")" ] || { echo "no checksum for $a in $sums" >&2; exit 1; }
done
cat <<RUBY
# Homebrew formula for the tap \`Na5co/homebrew-tap\` (brew install na5co/tap/polygo).
# Generated by scripts/formula.sh from the release's SHA256SUMS; do not edit by hand.
class Polygo < Formula
  desc "Translate app strings (xcstrings, Android, ARB, i18next, po, resx) via local LLM"
  homepage "https://github.com/Na5co/polygo"
  version "$v"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Na5co/polygo/releases/download/v#{version}/polygo-v#{version}-aarch64-darwin.tar.gz"
      sha256 "$(sha aarch64-darwin)"
    end
    on_intel do
      url "https://github.com/Na5co/polygo/releases/download/v#{version}/polygo-v#{version}-x86_64-darwin.tar.gz"
      sha256 "$(sha x86_64-darwin)"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Na5co/polygo/releases/download/v#{version}/polygo-v#{version}-aarch64-linux.tar.gz"
      sha256 "$(sha aarch64-linux)"
    end
    on_intel do
      url "https://github.com/Na5co/polygo/releases/download/v#{version}/polygo-v#{version}-x86_64-linux.tar.gz"
      sha256 "$(sha x86_64-linux)"
    end
  end

  def install
    bin.install "polygo"
    generate_completions_from_executable(bin/"polygo", "completions")
  end

  test do
    assert_match "polygo", shell_output("#{bin}/polygo --version")
  end
end
RUBY
