//! Coverage table (`polygo status --markdown`).

use crate::core::Unit;
use crate::lockfile::{State, Status};

/// Regional-indicator flag for a locale; falls back to a language→country guess.
pub fn flag(locale: &str) -> String {
    let parts: Vec<&str> = locale.split(['-', '_']).collect();
    let region = parts
        .iter()
        .skip(1)
        .find(|p| p.len() == 2 && p.chars().all(|c| c.is_ascii_alphabetic()))
        .map(|p| p.to_ascii_uppercase())
        .or_else(|| {
            let lang = parts[0].to_ascii_lowercase();
            let cc = match lang.as_str() {
                "en" => "GB",
                "de" => "DE",
                "fr" => "FR",
                "es" => "ES",
                "it" => "IT",
                "pt" => "PT",
                "nl" => "NL",
                "ja" => "JP",
                "ko" => "KR",
                "zh" => "CN",
                "ru" => "RU",
                "uk" => "UA",
                "be" => "BY",
                "pl" => "PL",
                "cs" => "CZ",
                "sk" => "SK",
                "hu" => "HU",
                "ro" => "RO",
                "bg" => "BG",
                "el" => "GR",
                "tr" => "TR",
                "ar" => "SA",
                "he" | "iw" => "IL",
                "fa" => "IR",
                "hi" => "IN",
                "bn" => "BD",
                "th" => "TH",
                "vi" => "VN",
                "id" | "in" => "ID",
                "ms" => "MY",
                "sv" => "SE",
                "da" => "DK",
                "fi" => "FI",
                "nb" | "nn" | "no" => "NO",
                "is" => "IS",
                "et" => "EE",
                "lv" => "LV",
                "lt" => "LT",
                "sl" => "SI",
                "hr" => "HR",
                "sr" => "RS",
                "bs" => "BA",
                "mk" => "MK",
                "sq" => "AL",
                "ca" => "ES",
                "eu" => "ES",
                "gl" => "ES",
                "ga" => "IE",
                "cy" => "GB",
                "af" => "ZA",
                "sw" => "KE",
                "am" => "ET",
                "ka" => "GE",
                "hy" => "AM",
                "az" => "AZ",
                "kk" => "KZ",
                "uz" => "UZ",
                "mn" => "MN",
                "ur" => "PK",
                "ta" => "IN",
                "te" => "IN",
                "ml" => "IN",
                "kn" => "IN",
                "mr" => "IN",
                "gu" => "IN",
                "pa" => "IN",
                "ne" => "NP",
                "si" => "LK",
                "my" => "MM",
                "km" => "KH",
                "lo" => "LA",
                "fil" | "tl" => "PH",
                _ => return None,
            };
            Some(cc.to_string())
        });
    match region {
        Some(cc) => cc
            .chars()
            .map(|c| char::from_u32(0x1F1E6 + (c as u32 - 'A' as u32)).unwrap_or(c))
            .collect(),
        None => "🌐".to_string(),
    }
}

/// `(translated, applicable)` for a locale: everything that is not new/untranslated/
/// needs-review counts as translated; plural forms count only where they apply.
pub fn coverage(units: &[Unit], locale: &str, status: &Status) -> (usize, usize) {
    let applicable = units.iter().filter(|u| u.applies_to(locale)).count();
    let missing = status.count(locale, State::New)
        + status.count(locale, State::Untranslated)
        + status.count(locale, State::NeedsReview);
    (applicable.saturating_sub(missing), applicable)
}

pub fn markdown(units: &[Unit], locales: &[&str], status: &Status) -> String {
    let mut s = String::from("| Locale | Translated | Coverage |\n|---|---:|---:|\n");
    for l in locales {
        let (done, total) = coverage(units, l, status);
        let pct = (done * 100).checked_div(total).unwrap_or(100);
        s.push_str(&format!(
            "| {} {l} | {done} / {total} | {pct}% |\n",
            flag(l)
        ));
    }
    let base = units.iter().filter(|u| u.locales.is_none()).count();
    s.push_str(&format!(
        "\n{base} strings · {} locales · generated by [polygo](https://github.com/Na5co/polygo)\n",
        locales.len()
    ));
    s
}
